# Generated by Django 3.2.8 on 2022-03-10 02:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('janata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 10, 2, 25, 31, 892198, tzinfo=utc)),
        ),
    ]
