# Generated by Django 3.2.8 on 2022-03-10 13:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('janata', '0002_auto_20220310_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 10, 13, 40, 14, 75928, tzinfo=utc)),
        ),
    ]
