# Generated by Django 3.2.8 on 2022-03-11 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('janata', '0003_alter_stock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
