# Generated by Django 3.2.8 on 2022-03-12 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('janata', '0004_alter_stock_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['trade_code']},
        ),
    ]
