# Generated by Django 3.2.8 on 2021-12-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-create_date', 'title']},
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Food', 'Food'), ('Travel', 'Travel'), ('Music', 'Music'), (' Lifestyle', ' Lifestyle'), ('Fitness', 'Fitness'), ('Sports', 'Sports'), ('News', 'News'), ('Entertainment', 'Entertainment'), ('Healthcare', 'Healthcare')], max_length=255),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
