# Generated by Django 3.2.8 on 2021-12-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20211223_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Travel', 'Travel'), ('Music', 'Music'), (' Lifestyle', ' Lifestyle'), ('Fitness', 'Fitness'), ('Sports', 'Sports'), ('News', 'News'), ('Entertainment', 'Entertainment'), ('Healthcare', 'Healthcare')], max_length=255),
        ),
    ]
